# Generated by Django 6.0.3 on 2026-03-31 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الدين المستحق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='الباركود')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر البيع')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='الكمية بالمخزن')),
                ('alert_threshold', models.IntegerField(default=10, verbose_name='حد التنبيه')),
                ('min_order_quantity', models.IntegerField(default=1, verbose_name='أقل كمية للطلب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد المستحق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المعالجة'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='المدفوع')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الخصم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي الجزئي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.product', verbose_name='الصنف')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder', verbose_name='فاتورة الشراء')),
            ],
            options={
                'verbose_name': 'عنصر شراء',
                'verbose_name_plural': 'عناصر الشراء',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المعالجة'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('returned', 'مرتجع')], default='completed', max_length=20, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('partial', 'مدفوع جزئياً'), ('unpaid', 'غير مدفوع')], default='paid', max_length=20, verbose_name='حالة الدفع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='المدفوع')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الخصم')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الضريبة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='core.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الإجمالي الجزئي')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر التكلفة')),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الربح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='core.product', verbose_name='الصنف')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesorder', verbose_name='فاتورة البيع')),
            ],
            options={
                'verbose_name': 'عنصر بيع',
                'verbose_name_plural': 'عناصر البيع',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'إضافة للمخزن'), ('out', 'سحب من المخزن'), ('adjustment', 'تعديل مخزن'), ('return', 'مرتجع')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'حركة مخزن',
                'verbose_name_plural': 'حركات المخزن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.supplier', verbose_name='المورد'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير المحل'), ('cashier', 'كاشير'), ('storekeeper', 'أمين المخزن'), ('accountant', 'محاسب')], default='cashier', max_length=20, verbose_name='الصلاحية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='core_produc_barcode_5cc7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_ba410e_idx'),
        ),
    ]
